### ISSUE TITLE
Crash: Illegal callback invocation from native modules

### ISSUE THREAD

**Issue by vendramini** [Agontuk/react-native-geolocation-service#13]
Hi!

The app just crashed throwing this error:

```javascript
Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
       at com.agontuk.RNFusedLocation.SingleLocationUpdate.invokeSuccess(SingleLocationUpdate.java:93)
       at com.agontuk.RNFusedLocation.SingleLocationUpdate.access$300(SingleLocationUpdate.java:16)
       at com.agontuk.RNFusedLocation.SingleLocationUpdate$2.onLocationResult(SingleLocationUpdate.java:45)
       at com.google.android.gms.internal.zzcff.zzu(Unknown Source)
       at com.google.android.gms.common.api.internal.zzci.zzb(Unknown Source)
       at com.google.android.gms.common.api.internal.zzcj.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

It doesn't happens all the time, so I can't do a step-by-step debug.

**Comment by Agontuk** [comment]
This probably happens when user keeps requesting location without waiting for the response of previous request. You should add a disabled/loading state in your button till the current request returns a result (error/success). Hopefully it'll solve the issue.

**Comment by vendramini** [comment]
Hi, thanks for the response!

1. User opens the app, I do a request location.
2. Meanwhile the app is opened, I do a request inside a setTimeout.

The error happens on both situation: sometimes when I just open the app, sometimes by the time it's opened.

I will try to create a flag for request return.

Thanks.

**Comment by vomchik** [comment]
@Agontuk Thanks. But could we manage this in the native module?

**Comment by Agontuk** [comment]
A possible fix is to wrap the callback in a try/catch block and then ignore the error. I'll try it out and then do a new release.
