### ISSUE TITLE
The connection to Google Play services was lost

### ISSUE THREAD

**Issue by PocketDaniel** [Agontuk/react-native-geolocation-service#137]
I'm getting a crash saying "The connection to Google Play services was lost". This happens regularly, mostly after app reinstall / update.
The strangest part is that crash is occurring only on one particular device segment - for me it is Huawei ATU-L21. Also tested the app on some Samsung devices and did not get any issue there.

react-native: 0.59.2
react-native-geolocation-service: 1.1.0 (also tried 2.0.0 version - still getting same crash)
googlePlayServicesVersion: 16.0.0
OS: EMUI 8.0.0 (based on Android 8.0.0)
Device: Huawei ATU-L21

Firebase crash log:
```
Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.android.gms.common.api.ApiException: 8: The connection to Google Play services was lost
      at com.google.android.gms.tasks.zzu.getResult(:15)
      at com.agontuk.RNFusedLocation.RNFusedLocationModule$4.onComplete(RNFusedLocationModule.java:347)
      at com.google.android.gms.tasks.zzj.run(:4)
      at android.os.Handler.handleCallback(Handler.java:808)
      at android.os.Handler.dispatchMessage(Handler.java:101)
      at android.os.Looper.loop(Looper.java:166)
      at android.app.ActivityThread.main(ActivityThread.java:7529)
      at java.lang.reflect.Method.invoke(Method.java)
      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Agontuk** [comment]
Does this have to do anything with google revoking Huawei's license ? This error means an internal error occurred when trying to fetch location. Can you try with any other Huawei devices to see if this happens there too ?

**Comment by andrey-tsaplin** [comment]
Same here. 
react-native-geolocation-service version 2.0.1
For me it happens on HUAWEI phones only. But sure it can happens on any device in some circumstances.

As reported earlier: https://github.com/Agontuk/react-native-geolocation-service/issues/72

**Comment by cayodonatti** [comment]
Got the same issue on the following Samsung device: 
![image](https://user-images.githubusercontent.com/20991516/69568416-4ed23280-0f9a-11ea-82e6-0432e6d812e0.png)

"react-native-geolocation-service": "^3.1.0"

**Comment by andrey-tsaplin** [comment]
@Agontuk Fixed in pull request above
