### ISSUE TITLE
App crashes when import RNFusedLocationPackage in mainApplication.java

### ISSUE THREAD

**Issue by sallarahmed** [Agontuk/react-native-geolocation-service#138]
application crashes at start when i import and call RNFusedLocationPackage() every possible solution i have tried but same issue.
react version: 0.59.8

logs:

2019-10-16 03:09:52.875 25783-25817/com.salesflosight E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: com.salesflosight, PID: 25783
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source)
        at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:96)
        at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120)
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.salesflosight-1/base.apk"],nativeLibraryDirectories=[/data/app/com.salesflosight-1/lib/arm, /data/app/com.salesflosight-1/base.apk!/lib/armeabi-v7a, /oem/lib, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source) 
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source) 
        at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:96) 
        at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26) 
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42) 
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41) 
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1212) 
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1182) 
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1120) 
        at com.facebook.react.ReactInstanceManager.access$900(ReactInstanceManager.java:123) 
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:943) 
        at java.lang.Thread.run(Thread.java:761)

**Comment by Agontuk** [comment]
You're probably using other google play service libraries in your project and they're using different versions than location service. You have to make sure all play service libraries use the same version.

**Comment by sallarahmed** [comment]
problem has been resolved by exclude method adding play service version 16 in gradle file thanks for your kind response

**Comment by cinder92** [comment]
@sallarahmed which version did you use? can you share the codE?

**Comment by sallarahmed** [comment]
i was on

**Comment by sallarahmed** [comment]
I was on .59.8

**Comment by rahamin1** [comment]
I am using 59.9.

I didn't have any reference to `googlePlayServicesVersion` in my project's folder.
I do have  project-wide properties in my root build.gradle, so I have added, as explained [here](https://github.com/Agontuk/react-native-geolocation-service#android), `googlePlayServicesVersion = "16.0.0"`.

I have attached below my root build.gradle file.
When I try running the app, it is crashing. If I remove `googlePlayServicesVersion = "16.0.0"`, the build fails with the error:
`com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\Users\yossi\.gradle\caches\transforms-2\files-2.1\1e40268b8acdb25a528b0d10b5f31a2a\jars\classes.jar
`
**Any idea how to fix this?**

### build.gradle:
```

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 19
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        googlePlayServicesVersion = "16.0.0"
    }
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.0")
    }
}

```
