### ISSUE TITLE
Crash when app start : Illegal class access: 'com.google.android.gms.location.FusedLocationProviderClient'

### ISSUE THREAD

**Issue by kidmysoul** [Agontuk/react-native-geolocation-service#14]
I followed every step in android and the build success but when app start I got this error:

`java.lang.IllegalAccessError: Illegal class access: 'com.google.android.gms.location.FusedLocationProviderClient' attempting to access 'com.google.android.gms.internal.zzbce' (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/com.mynew.unlog-QrqAHGWseTtHezcO8qIiAw==/base.apk)`

this is my build.gradle:

dependencies {
    compile project(':react-native-dialogs') 
    compile project(':react-native-fetch-blob')
    compile project(':react-native-image-picker')
    compile project(':react-native-fbsdk')
    compile project(':react-native-admob')
    compile project(':react-native-svg')
    compile project(':react-native-vector-icons')
    compile project(':react-native-spinkit')
    compile project(':react-native-mail')
    compile project(':react-native-device-info')
    compile project(':react-native-geolocation-service')
    compile fileTree(dir: "libs", include: ["*.jar"])
    // From node_modules
    compile 'com.android.support:appcompat-v7:25.0.2'
    compile 'com.facebook.react:react-native:+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:25.3.1'
}

**Comment by Agontuk** [comment]
You probably have to set play-services-base to 11.0.0. Also try checking all the module dependencies via `./gradlew app:dependencies` and see if you missed any play service module.

**Comment by kidmysoul** [comment]
@Agontuk  maybe you are right but now I have switched back to the RN geolocation so I cannot confirm whether it's right or not.But thank you for fast replay.

**Comment by DevilPatels** [comment]
i having issue like this

this is my logcat

java.lang.NoSuchMethodError: No static method getFusedLocationProviderClient(Landroid/content/Context;)Lcom/google/android/gms/location/FusedLocationProviderClient; in class Lcom/google/android/gms/location/LocationServices; or its super classes (declaration of 'com.google.android.gms.location.LocationServices' appears in /data/app/com.drapp-C1klWmBxCroOYpKkCWvoAw==/base.apk!classes2.dex)
        at com.airbnb.android.react.maps.FusedLocationSource.<init>(FusedLocationSource.java:22)
        at com.airbnb.android.react.maps.AirMapView.<init>(AirMapView.java:165)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:85)
        at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:29)
        at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
        at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:270)
        at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:180)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations(UIViewOperationQueue.java:987)
        at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:958)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1083)
        at android.view.Choreographer.doCallbacks(Choreographer.java:908)
        at android.view.Choreographer.doFrame(Choreographer.java:831)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1070)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:228)
        at android.app.ActivityThread.main(ActivityThread.java:7782)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

could anyone find solution for this ?
