### ISSUE TITLE
App crashes when react-native-geolocation-service and react-native-maps modules are installed together

### ISSUE THREAD

**Issue by MihaiGitHub** [Agontuk/react-native-geolocation-service#162]
**Bug**
react-native-geolocation-service does not work with react-native-maps module in the same project. App crashes on load. Once react-native-geolocation-service module is removed from the project, the app works fine.

react-native-geolocation-service is needed to get the users location, because it is more accurate than the javascript navigator object.

https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

**Environment info**
System:
OS: Windows 10 10.0.18362
CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
Memory: 7.14 GB / 15.95 GB
Binaries:
Node: 12.15.0 - C:\Program Files\nodejs\node.EXE
npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
SDKs:
Android SDK:
API Levels: 23, 24, 25, 26, 27, 28
Build Tools: 23.0.1, 23.0.2, 23.0.3, 26.0.1, 26.0.3, 27.0.3, 28.0.3
System Images: android-23 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
IDEs:
Android Studio: Version 3.5.0.0 AI-191.8026.42.35.5791312
npmPackages:
react: 16.9.0 => 16.9.0
react-native: 0.61.5 => 0.61.5

**Library version**
react-native-maps => 0.26.1
react-native-geolocation-service => ^4.0.0

**Steps To Reproduce**
Sample app provided below which shows that the 2 modules don't work together as expected:

Download the sample app below, install dependencies, and try to run it.
https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

npm install
npm run android

**Describe what you expected to happen:**

App will crash on load.
Reproducible sample code
https://bitbucket.org/mihailiviu/react-native-maps-geolocation/src/master/

**Comment by CharlesMenier** [comment]
We have a similar problem on my project but at compiling time :


```
* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.google.android.gms:play-services-location:16.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
       - https://jcenter.bintray.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
       - https://maven.google.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://maven.google.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
     Required by:
         project :app > project :react-native-geolocation-service
   > Could not find com.google.android.gms:play-services-location:16.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
       - https://jcenter.bintray.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://jcenter.bintray.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
       - https://maven.google.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.pom
       - https://maven.google.com/com/google/android/gms/play-services-location/16.1.0/play-services-location-16.1.0.jar
     Required by:
         project :app > project :react-native-google-places > com.google.android.libraries.places:places:1.1.0
```

And when trying to switch to version 16.0.0 of com.google.android.gms:play-services-location we get another error

```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/Users/myuser/dev/myproject/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 130

* What went wrong:
Execution failed for task ':app:generatePackageList'.
> ReactNativeModules$_generatePackagesFile_closure3
```

**Comment by MihaiGitHub** [comment]
This is what I pulled from logkitty and a screenshot of what it looks like on the emulator:

```
$ react-native log-android
info Starting logkitty
[13:36:06] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[13:36:07] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()
                           └ ReactInstanceManager.recreateReactContextInBackground()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.runCreateReactContextOnNewThread()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[13:36:12] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[13:36:12] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()
                           └ CatalystInstanceImpl.initialize()

[13:36:12] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[13:36:13] D | ReactNative ▶︎ ReactInstanceManager.detachViewFromInstance()

[13:36:21] D | ReactNative ▶︎ ReactInstanceManager.ctor()

[13:36:21] D | ReactNative ▶︎ ReactInstanceManager.createReactContextInBackground()
                           └ ReactInstanceManager.recreateReactContextInBackgroundInner()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.onJSBundleLoadedFromServer()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.recreateReactContextInBackground()
                           └ ReactInstanceManager.runCreateReactContextOnNewThread()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.createReactContext()

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge.

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge before initializeBridge

[13:36:26] D | ReactNative ▶︎ Initializing React Xplat Bridge after initializeBridge

[13:36:26] D | ReactNative ▶︎ CatalystInstanceImpl.runJSBundle()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.setupReactContext()

[13:36:26] D | ReactNative ▶︎ CatalystInstanceImpl.initialize()

[13:36:26] D | ReactNative ▶︎ ReactInstanceManager.attachRootViewToInstance()

[13:36:27] D | ReactNative ▶︎ ReactInstanceManager.detachViewFromInstance()
```
![image](https://user-images.githubusercontent.com/5934128/75069955-883e0f80-54af-11ea-9d9c-1c96fd66f5cc.png)

**Comment by valeriashpiner** [comment]
Same for me

**Comment by Agontuk** [comment]
None of the logs are giving any info related to the crash. Can you guys paste the full logs here so that I can find the issue ? Although it seems to me the crash is related to the play service library version mismatch. You have to use same version for both play-services-location & play-services-maps library.

**Comment by silviodaminato** [comment]
Hello, I think I have the same problem. As far as I can see it happens on Android 10, but I cannot guarantee that it happens only there.

Here are my logs:
`2020-03-23 09:27:26.658 18305-18416/com.silviodaminato.airquality E/AndroidRuntime: FATAL EXCEPTION: create_react_context
    Process: ******
    java.lang.NoSuchMethodError: No static method isAtLeastR()Z in class Landroidx/core/os/BuildCompat; or its super classes (declaration of 'androidx.core.os.BuildCompat' appears in /data/app/com.silviodaminato.airquality-1GTwqTdN8kWa9gHAGDELtg==/base.apk)
        at com.google.android.gms.common.util.PlatformVersion.isAtLeastR(com.google.android.gms:play-services-basement@@17.2.0:21)
        at com.google.android.gms.common.api.GoogleApi.zaa(com.google.android.gms:play-services-base@@17.2.0:128)
        at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.0:41)
        at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.0:56)
        at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
        at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
        at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:123)
        at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
        at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
        at java.lang.Thread.run(Thread.java:919)
`
Hope to find a solution.
Thank you!

**Comment by zabkwak** [comment]
Updated play-services versions in my app build.gradle and it seems working.
```
implementation 'com.google.android.gms:play-services-base:17.0.0'
implementation 'com.google.android.gms:play-services-maps:17.0.0'
```
And changed version in the module build.gradle
`def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "17.0.0"`

RN 0.61.5
module 4.0.0
rn-maps 0.26.1

**Comment by Agontuk** [comment]
> Hello, I think I have the same problem. As far as I can see it happens on Android 10, but I cannot guarantee that it happens only there.
> 
> Here are my logs:
> 
> ```
>     Process: ******
>     java.lang.NoSuchMethodError: No static method isAtLeastR()Z in class Landroidx/core/os/BuildCompat; or its super classes (declaration of 'androidx.core.os.BuildCompat' appears in /data/app/******/base.apk)
>         at com.google.android.gms.common.util.PlatformVersion.isAtLeastR(com.google.android.gms:play-services-basement@@17.2.0:21)
>         at com.google.android.gms.common.api.GoogleApi.zaa(com.google.android.gms:play-services-base@@17.2.0:128)
>         at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.0:41)
>         at com.google.android.gms.common.api.GoogleApi.<init>(com.google.android.gms:play-services-base@@17.2.0:56)
>         at com.google.android.gms.location.FusedLocationProviderClient.<init>(Unknown Source:8)
>         at com.google.android.gms.location.LocationServices.getFusedLocationProviderClient(Unknown Source:2)
>         at com.agontuk.RNFusedLocation.RNFusedLocationModule.<init>(RNFusedLocationModule.java:123)
>         at com.agontuk.RNFusedLocation.RNFusedLocationPackage.createNativeModules(RNFusedLocationPackage.java:26)
>         at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:41)
>         at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:41)
>         at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1230)
>         at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1201)
>         at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1134)
>         at com.facebook.react.ReactInstanceManager.access$1000(ReactInstanceManager.java:125)
>         at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:951)
>         at java.lang.Thread.run(Thread.java:919)
> ```
> 
> Hope to find a solution.
> Thank you!

play service library version mismatch. You have to use same version for both play-services-location & play-services-maps library. You can set your preferred version in `ext` block in `build.gradle` file using `googlePlayServicesVersion` variable.

**Comment by Agontuk** [comment]
Closing due to inactivity, also not an issue related to the library. Please check the example project, it runs fine with react-native-maps.
