### ISSUE TITLE
Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult'

### ISSUE THREAD

**Issue by oakis** [Agontuk/react-native-geolocation-service#38]
Log from Crashlytics:
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startIntentSenderForResult(android.content.IntentSender, int, android.content.Intent, int, int, int)' on a null object reference
       at com.google.android.gms.common.api.Status.startResolutionForResult(Unknown Source)
       at com.google.android.gms.common.api.ResolvableApiException.startResolutionForResult(Unknown Source)
       at com.agontuk.RNFusedLocation.RNFusedLocationModule.onComplete(RNFusedLocationModule.java:127)
       at com.google.android.gms.tasks.zzf.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Google Play Services: On
Wifi: On
Android 7.0.
Galaxy S6 Edge+.
User had version 1.0.3 of react-native-geolocation-service.

FYI: Users on my latest version have 1.0.4 of react-native-geolocation-service.

**Comment by Agontuk** [comment]
This should be fixed from 1.0.3, please let me know if it happens on 1.0.4 or above.

**Comment by oakis** [comment]
@Agontuk Thanks, I will keep my eyes open.

**Comment by Agontuk** [comment]
Closing due to inactivity.
