### ISSUE TITLE
App crashes or could not invoke Geolocation.getCurrentPosition

### ISSUE THREAD

**Issue by swatiredhu17** [Agontuk/react-native-geolocation-service#398]
## Environment
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 29.25 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/****/node_modules/.bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.0 => 0.67.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms
Android

## Versions
Please add the used versions/branches
 - Android : used implementation 'com.google.android.gms:play-services-location:21.0.1'
- react-native-geolocation-service:"^5.3.1"
- react-native: "0.67.0",
- react:"17.0.2",

## Description
**Caused by: java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected** (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~bD1cPSXr3jYigB864Ni0yw==/com.truecharger-IyI3jbMZVzNj2aO7gf6B4g==/base.apk!classes14.dex)
                                                                                                    	at com.agontuk.RNFusedLocation.FusedLocationProvider.getCurrentLocation(FusedLocationProvider.java:97)
                                                                                                    	at com.agontuk.RNFusedLocation.RNFusedLocationModule.getCurrentPosition(RNFusedLocationModule.java:112)

```
Exception in native call
                                                                                                    java.lang.RuntimeException: Could not invoke RNFusedLocation.getCurrentPosition
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
                                                                                                    Caused by: java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~bD1cPSXr3jYigB864Ni0yw==/com.truecharger-IyI3jbMZVzNj2aO7gf6B4g==/base.apk!classes14.dex)
                                                                                                    	at com.agontuk.RNFusedLocation.FusedLocationProvider.getCurrentLocation(FusedLocationProvider.java:97)
                                                                                                    	at com.agontuk.RNFusedLocation.RNFusedLocationModule.getCurrentPosition(RNFusedLocationModule.java:112)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)


```

## Reproducible Demo
 
1. Add below in android/app/gradle to use latest version 
`implementation 'com.google.android.gms:play-services-location:21.0.1' 
  implementation (project(path: ':react-native-geolocation-service')) {
    exclude group: 'com.google.android.gms', module: 'play-services-location'
    }`
2. When user allow for permission in android pop-up, either it crashes or give above error 

## Expected Results

getCurrentLocation should return values

## Note: 

similar to https://github.com/Agontuk/react-native-geolocation-service/issues/367

**Comment by mohdzaifquraishi-greenapex** [comment]
Any solution ?

**Comment by curtisgibeaut** [comment]
This is occurring for me with 22.50.14 of google play services as well.

**Comment by bicanezin** [comment]
Any solution?

**Comment by riku99** [comment]
@mohdzaifquraishi-greenapex @curtisgibeaut @bicanezin 

Try putting this in the ext block of android/build.gradle.

```
googlePlayServicesVersion = "21.0.1"
```

**Comment by LinaEfer** [comment]
> @mohdzaifquraishi-greenapex @curtisgibeaut @bicanezin
> 
> Try putting this in the ext block of android/build.gradle.
> 
> ```
> googlePlayServicesVersion = "21.0.1"
> ```

Hello, this solution doesn't work in case if you have other libraries with `googlePlayServices` dependencies.
Like, by declaring `googlePlayServicesVersion = "21.0.1"` you force every module dependency switch to `"21.0.1"`, in case if this version doesn't existe you got build error.

An exemple : 
- `react-native-device-info` has `com.google.android.gms.play-services-iid` module, which is latest version 17.0.0. 

-----
In my case this error is still present : 
- "react": "18.2.0",
- "react-native": "^0.71.8",
- "react-native-geolocation-service": "^5.3.1",
- `android/app/build.gradle` -> `implementation "com.google.android.gms:play-services-location:21.0.1"`

So, still the same question: **any idea ?** 🙏

**Comment by bicanezin** [comment]
@LinaEfer 
My case and the 'solution': after including this dependency in the project, I had this issue when I deleted the yarn.lock and node_modules. I noticed that by keeping the project's yarn.lock while it was working, I no longer had any problems.

**Comment by LinaEfer** [comment]
@bicanezin Unfortunately in my case full clean up (node_modules + yarn.lock, pods, android sync prject & gradle files) doesn't fix the issue :( 

> @LinaEfer My case and the 'solution': after including this dependency in the project, I had this issue when I deleted the yarn.lock and node_modules. I noticed that by keeping the project's yarn.lock while it was working, I no longer had any problems.

**Comment by SulthanYS** [comment]
> @mohdzaifquraishi-greenapex @curtisgibeaut @bicanezin
> 
> Try putting this in the ext block of android/build.gradle.
> 
> ```
> googlePlayServicesVersion = "21.0.1"
> ```

Locking a particular googlePlayServicesVersion, is a best practices?

**Comment by vsheyanov** [comment]
Possible solution: check my response to `react-native-maps` module which changed location module version and broke our app:
https://github.com/react-native-maps/react-native-maps/pull/4858#issuecomment-1777470683

BTW, documentation for the library literally says lock to version 17:
https://github.com/Agontuk/react-native-geolocation-service/blob/87448a0ab8c9bcc6c2ab0cc8b2db019ae5b400fd/docs/setup.md#1-linking-1

**Comment by SulthanYS** [comment]
> Possible solution: check my response to `react-native-maps` module which changed location module version and broke our app: [react-native-maps/react-native-maps#4858 (comment)](https://github.com/react-native-maps/react-native-maps/pull/4858#issuecomment-1777470683)
> 
> BTW, documentation for the library literally says lock to version 17: https://github.com/Agontuk/react-native-geolocation-service/blob/87448a0ab8c9bcc6c2ab0cc8b2db019ae5b400fd/docs/setup.md#1-linking-1

Thanks for the info @vsheyanov I'll check from my side and share info here

**Comment by vsheyanov** [comment]
@SulthanYS I updated my answer with a command `./gradlew app:dependencies` that helped me to find `rn-maps` library that updated `location` dependency that was causing problems.
In our case `googlePlayServicesVersion` with version > 20 was resulting in a crash.

**Comment by riku99** [comment]
@LinaEfer 

You might want to try modifying the build.gradle file of react-native-geolocation-service directly.

Change this line:

```
implementation "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
```

to:

```
implementation "com.google.android.gms:play-services-location:21.0.1"
```

However, I haven't actually tested this myself as I am not using react-native-device-info.

**Comment by Danushka96** [comment]
Any solution for this issue?

**Comment by phatlaunchdeck** [comment]
So far @riku99's workaround is the way to go, I can confirm it's working with React Native 72 and latest version of `react-native-device-info`.

**Comment by kimthompson** [comment]
The solutions here didn't quite work for me, but the one [here](https://stackoverflow.com/a/77307617) did. It's extremely similar, except in android/gradle.build I set  `playServicesLocationVersion` instead of `googlePlayServicesVersion`.

**Comment by AbaidullahRajpoot** [comment]
Certainly! If you are using React Native version 0.71 and need to update the Google Play Services location dependency, follow these steps:

1. In android/app/build.gradle:
Add the following line to the dependencies section:

dependencies {
    // other dependencies

    implementation("com.google.android.gms:play-services-location:21.0.1") //add this line
}


2. In android/build.gradle:
Add the googlePlayServicesVersion in the ext block within the buildscript section:

buildscript {
    ext {
        // other configurations
        googlePlayServicesVersion = "21.0.1" //add this line
    }
    // other configurations
}

**Comment by andrecrimb** [comment]
Thanks @riku99 it solves the issue 🙏🏽

**Comment by AftabUfaq** [comment]
a solution for this is . go to file  **node_modules\react-native-geolocation-service\android\build.gradle** and change the this line
 
`def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "18.0.0"` 
to 
`def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "21.0.1"`

and all like this  


```
dependencies {
   implementation "com.facebook.react:react-native:+"
  implementation 'androidx.appcompat:appcompat:1.0.2'
  implementation "com.google.android.gms:play-services-location:21.0.1"
}
```


and patch the package with yarn patch-package react-native-geolocation-service


and your issue will be gone

**Comment by usamaabutt** [comment]
> @LinaEfer
> 
> You might want to try modifying the build.gradle file of react-native-geolocation-service directly.
> 
> Change this line:
> 
> ```
> implementation "com.google.android.gms:play-services-location:$googlePlayServicesVersion"
> ```
> 
> to:
> 
> ```
> implementation "com.google.android.gms:play-services-location:21.0.1"
> ```
> 
> However, I haven't actually tested this myself as I am not using react-native-device-info.

It fixed my crash. Thanks!

**Comment by Bilal-Abdeen** [comment]
As @kimthompson indicated, updating `android/build.gradle` and `android/app/build.gradle` throws an error for me. Updating ONLY `android/build.gradle` worked perfectly.
```gradle 
buildscript {
 ext {
   // .....
   playServicesLocationVersion = "21.0.1" // add this 
   // .....
  }
}

**Comment by rider-cantuaria-eng** [comment]
remove the react-native-geolocation-service and install npm install react-native-fused-location, this lib works.

**Comment by gnvcor** [comment]
@Bilal-Abdeen it's work, thx!

**Comment by awais882s** [comment]
@AftabUfaq Thank you brother
Working fine now

**Comment by RaghavStepron** [comment]
(Aug 2024)
Go to file _**node_modules\react-native-geolocation-service\android\build.gradle**_ and change

```def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "18.0.0"```
to
```def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "21.0.1"```

**Comment by pestrige** [comment]
> (Aug 2024) Go to file _**node_modules\react-native-geolocation-service\android\build.gradle**_ and change
> 
> `def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "18.0.0"` to `def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "21.0.1"`

works like a charm!

**Comment by awais882s** [comment]
> > (Aug 2024) Go to file _**node_modules\react-native-geolocation-service\android\build.gradle**_ and change
> > `def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "18.0.0"` to `def DEFAULT_GOOGLE_PLAY_SERVICES_VERSION = "21.0.1"`
> 
> works like a charm!

Thank you sir

**Comment by Dazzlin-32** [comment]
> @mohdzaifquraishi-greenapex @curtisgibeaut @bicanezin
> 
> Try putting this in the ext block of android/build.gradle.
> 
> ```
> googlePlayServicesVersion = "21.0.1"
> ```

This worked for me, Thank you so much

**Comment by owen2345** [comment]
`googlePlayServicesVersion = "21.0.1"`
it worked for me too. Thank you

**Comment by nat-jones** [comment]
How would you accomplish this in an expo-managed project?

**Comment by a2zcreatorzTeam** [comment]
googlePlayServicesVersion = "21.0.1"
it worked for me too. Thank you
