### ISSUE TITLE
The connection to Google Play services was lost

### ISSUE THREAD

**Issue by JanErikFoss** [Agontuk/react-native-geolocation-service#72]
I've got this error in my crashlytics log. 

react-native-geolocation-service 2.0.1
react-native 0.59.5
googlePlayServicesVersion = "16.0.0"
android 10
Pixel 3

> Fatal Exception: com.google.android.gms.tasks.RuntimeExecutionException: com.google.android.gms.common.api.ApiException: 8: The connection to Google Play services was lost
       at com.google.android.gms.tasks.zzu.getResult(Unknown Source:15)
       at com.agontuk.RNFusedLocation.RNFusedLocationModule$4.onComplete(RNFusedLocationModule.java:347)
       at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7116)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

**Comment by Agontuk** [comment]
Not sure what's causing this, is it happening frequently ?

**Comment by JanErikFoss** [comment]
Just once.

**Comment by oakis** [comment]
> Just once.

Could just be a coincidence then.

**Comment by Agontuk** [comment]
Closing due to inactivity, please open a new issue if this happens again.
