### ISSUE TITLE
Crash when start up

### ISSUE THREAD

**Issue by sandropoluan** [Agontuk/react-native-geolocation-service#9]
My App get crash when starting up.
This issue might be related with  react-native-smart-splash-screen.
But I post here because I was not have this issue until I use this lib.
```
02-25 23:11:37.374  2931  2931 E WindowManager: android.view.WindowLeaked: Activity com.eabsen.MainActivity has leaked window DecorView@9d1f8db[] that was originally added here
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:418)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.Dialog.show(Dialog.java:322)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.reactnativecomponent.splashscreen.RCTSplashScreen$1.run(RCTSplashScreen.java:73)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.Activity.runOnUiThread(Activity.java:5866)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.reactnativecomponent.splashscreen.RCTSplashScreen.openSplashScreen(RCTSplashScreen.java:49)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.reactnativecomponent.splashscreen.RCTSplashScreen.openSplashScreen(RCTSplashScreen.java:39)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.reactnativecomponent.splashscreen.RCTSplashScreen.openSplashScreen(RCTSplashScreen.java:35)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.eabsen.MainActivity.onCreate(MainActivity.java:20)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.Activity.performCreate(Activity.java:6679)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.ActivityThread.-wrap12(ActivityThread.java)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.os.Looper.loop(Looper.java:154)
02-25 23:11:37.374  2931  2931 E WindowManager:         at android.app.ActivityThread.main(ActivityThread.java:6119)
02-25 23:11:37.374  2931  2931 E WindowManager:         at java.lang.reflect.Method.invoke(Native Method)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-25 23:11:37.374  2931  2931 E WindowManager:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

After I uninstall this lib, everything back to normal.

**Comment by devLaaziz** [comment]
+++

**Comment by Agontuk** [comment]
@sandropoluan, can you provide a demo which reproduces this issue? I tried integrating the library in my example project and it worked fine.

**Comment by moh3n9595** [comment]
same issue

**Comment by Agontuk** [comment]
Closing due to inactivity, please provide a sample project if you're still facing this issue.
